USE master
GO
IF DB_ID('CHATTING_APP_21127665') IS NOT NULL
	DROP DATABASE CHATTING_APP_21127665
GO
CREATE DATABASE CHATTING_APP_21127665
GO
USE CHATTING_APP_21127665
GO

CREATE TABLE ACCOUNTS
(
	USERNAME NVARCHAR(30),
	PASSWORD NVARCHAR(30) NOT NULL

	CONSTRAINT PK_ACCOUNT 
	PRIMARY KEY (USERNAME)
)
CREATE TABLE GROUPS 
(
	GROUP_ID CHAR(8),
	GROUP_NAME NVARCHAR(100) NOT NULL,
	OWNER NVARCHAR(30) NOT NULL

	CONSTRAINT PK_GROUPS
	PRIMARY KEY(GROUP_ID)
	CONSTRAINT FK_GROUPS
	FOREIGN KEY(OWNER)
	REFERENCES ACCOUNTS
)
CREATE TABLE GROUP_MEMBERS
(
	GROUP_ID CHAR(8),
	MEMBER_NAME NVARCHAR(30)

	CONSTRAINT PK_GROUP_MEMBERS
	PRIMARY KEY(GROUP_ID, MEMBER_NAME),
	CONSTRAINT FK_GM_G
	FOREIGN KEY(GROUP_ID)
	REFERENCES GROUPS,
	CONSTRAINT FK_GM_A
	FOREIGN KEY(MEMBER_NAME)
	REFERENCES ACCOUNTS
)
CREATE TABLE CHAT_HISTORY
(
	ID CHAR(8),
	SENDER NVARCHAR(30),
	RECEIVER NVARCHAR(30),
	CONTENT NVARCHAR(200) NOT NULL

	CONSTRAINT PK_CHAT_HISTORY
	PRIMARY KEY(ID, SENDER, RECEIVER),
	CONSTRAINT FK_CH_A
	FOREIGN KEY(SENDER)
	REFERENCES ACCOUNTS,
	CONSTRAINT FK_CH_A2
	FOREIGN KEY(RECEIVER)
	REFERENCES ACCOUNTS,
)