USE master
GO
IF DB_ID('CHATTING_APP_21127665') IS NOT NULL
	DROP DATABASE CHATTING_APP_21127665
GO
CREATE DATABASE CHATTING_APP_21127665
GO
USE CHATTING_APP_21127665
GO

CREATE TABLE ACCOUNTS
(
    USERNAME NVARCHAR(30),
    PASSWORD NVARCHAR(30) NOT NULL

        CONSTRAINT PK_ACCOUNT
        PRIMARY KEY (USERNAME)
)
CREATE TABLE GROUPS
(
    GROUP_NAME NVARCHAR(50),
    OWNER NVARCHAR(30)

        CONSTRAINT PK_GROUPS
        PRIMARY KEY(GROUP_NAME, OWNER)
        CONSTRAINT FK_GROUPS
        FOREIGN KEY(OWNER)
        REFERENCES ACCOUNTS
)
CREATE TABLE GROUP_MEMBERS
(
    GROUP_NAME NVARCHAR(50),
    OWNER NVARCHAR(30),
    MEMBER_NAME NVARCHAR(30)

        CONSTRAINT PK_GROUP_MEMBERS
        PRIMARY KEY(GROUP_NAME, OWNER, MEMBER_NAME),
    CONSTRAINT FK_GM_G
        FOREIGN KEY (GROUP_NAME, OWNER)
            REFERENCES GROUPS,
    FOREIGN KEY(MEMBER_NAME)
        REFERENCES ACCOUNTS
)
CREATE TABLE CHAT_HISTORY
(
    SENDER NVARCHAR(30),
    RECEIVER NVARCHAR(131),
    CONTENT NVARCHAR(200) NOT NULL,
    TYPE NVARCHAR(10),
    ORDER_INDEX INT

        CONSTRAINT PK_CHAT_HISTORY
            PRIMARY KEY(ORDER_INDEX, SENDER, RECEIVER),
    CONSTRAINT FK_CH_A
        FOREIGN KEY(SENDER)
            REFERENCES ACCOUNTS,
)